"""Trace the Fortuity apex triangle into vector outlines.

The mark ships as a 914x661 PNG - fine on screen, soft as a full-page
watermark. Tracing it once turns it into a path that stays crisp at any size
and costs a few KB in the PDF instead of a bitmap on every page.

    python3 tools/trace_apex.py <source.png> src/apex_path.py
"""

import sys

import numpy as np
import potrace
from PIL import Image, ImageFilter

# artwork bounds inside the source PNG
CROP = (136, 76, 762, 618)
SCALE = 2
BLUR = 1.5


def trace(src):
    alpha = Image.open(src).convert("RGBA").getchannel("A").crop(CROP)
    w, h = alpha.size
    big = alpha.resize((w * SCALE, h * SCALE), Image.LANCZOS)
    big = big.filter(ImageFilter.GaussianBlur(BLUR))
    # potracer reads truthy cells as background, so the mask is inverted:
    # pass the transparent area as True and the artwork traces as ink.
    bitmap = potrace.Bitmap(np.array(big) <= 128)
    path = bitmap.trace(turdsize=60, alphamax=1.0, opticurve=True, opttolerance=0.6)

    bw, bh = float(w * SCALE), float(h * SCALE)

    def pt(p):
        # normalise into a unit box and flip to PDF's y-up orientation
        return round(p.x / bw, 5), round(1.0 - p.y / bh, 5)

    out = []
    for curve in path:
        segs = [("m", pt(curve.start_point))]
        for s in curve.segments:
            if s.is_corner:
                segs.append(("l", pt(s.c)))
                segs.append(("l", pt(s.end_point)))
            else:
                segs.append(("c", pt(s.c1), pt(s.c2), pt(s.end_point)))
        segs.append(("z",))
        out.append(segs)
    return out, w / float(h)


if __name__ == "__main__":
    src, dst = sys.argv[1], sys.argv[2]
    curves, aspect = trace(src)
    n = sum(len(c) for c in curves)
    with open(dst, "w", encoding="utf-8") as fh:
        fh.write('"""Vector outline of the Fortuity apex triangle.\n\n'
                 "Generated by tools/trace_apex.py from the 4C transparent PNG.\n"
                 "Coordinates are normalised to a unit box, y-up, ready to scale.\n"
                 'Do not hand-edit - re-run the tracer instead.\n"""\n\n')
        fh.write(f"ASPECT = {aspect:.6f}\n\nCURVES = [\n")
        for c in curves:
            fh.write("    [\n")
            for seg in c:
                fh.write(f"        {seg!r},\n")
            fh.write("    ],\n")
        fh.write("]\n")
    print(f"wrote {dst}: {len(curves)} curves, {n} ops, aspect {aspect:.4f}")
